package com.exiro.render;

public enum ButtonType {

    HOUSE, AGRICULTURE, INDUSTRY, MARKET, HEALTH, PALACE, CULTURE, TEMPLE, ARMY, CACHET, MAPVIEW,

    HOUSE_LITTLE, HOUSE_BIG,

    AGRICULTURE_FARM, AGRICULTURE_FISH, AGRICULTURE_VITICULTURE, AGRICULTURE_BREEDING,

    INDUSTRY_1, INDUSTRY_2,

    MARKET_GRANARY, MARKET_STOCK, MARKET_AGORA, MARKET_TRANS,

    HEALTH_WATER, HEALTH_HOSPITAL, HEALTH_SAFETY, HEALTH_GUARD,

    PALACE_PALACE, PALACE_TAX, PALACE_BRIDGE,

    CULTURE_PHILOSOPHIA, CULTURE_GYMNASIUM, CULTURE_DRAMA, CULTURE_STADIUM,

    TEMPLE_TEMPLE, TEMPLE_HEROE, TEMPLE_CONSTRUCT,

    ARMY_FORT, ARMY_BUILDING,

    CACHET_SIMPLE, CACHET_ADVANCED, CAHCHET_MONUMENT,


}
