package com.exiro.render;

public enum ButtonType {

    NONE,

    HOUSE, AGRICULTURE, INDUSTRY, MARKET, HEALTH, PALACE, CULTURE, TEMPLE, ARMY, CACHET, MAPVIEW,

    HOUSE_LITTLE, HOUSE_BIG,

    AGRICULTURE_FARM, AGRICULTURE_FISH, AGRICULTURE_VITICULTURE, AGRICULTURE_BREEDING,

    INDUSTRY_1, INDUSTRY_2,

    MARKET_GRANARY, MARKET_STOCK, MARKET_AGORA, MARKET_TRANS,

    HEALTH_WATER, HEALTH_HOSPITAL, HEALTH_SAFETY, HEALTH_GUARD,

    PALACE_PALACE, PALACE_TAX, PALACE_BRIDGE,

    CULTURE_PHILOSOPHIA, CULTURE_GYMNASIUM, CULTURE_DRAMA, CULTURE_STADIUM,

    TEMPLE_TEMPLE, TEMPLE_HEROE, TEMPLE_CONSTRUCT,

    ARMY_FORT, ARMY_BUILDING,

    CACHET_SIMPLE, CACHET_ADVANCED, CAHCHET_MONUMENT,

    QUICK_ROUTE, QUICK_STOP, QUICK_ERASE, QUICK_CANCEL, QUICK_HISTORY, QUICK_MISSION, QUICK_VIEW, QUICK_MAP,

    FARM_WHEAT, FARM_CARROT, FARM_ONION,

    BREEDING_SHEEPHOLD, BREEDING_SHEEP, BREEDING_DAIRY, BREEDING_GOAT,

    FISHING_FISHERY, FISHING_HUNTING,

    VITICULTURE_SMALLHOLDING, VITICULTURE_OLIVETREE, VITICULTURE_GRAPE,

    AGORA_AGORA, AGORA_FOOD, AGORA_WOOL, AGORA_OIL,

    INDUSTRY_FOUNDRY, INDUSTRY_GUILD, INDUSTRY_MARBLE, INDUSTRY_MINT, INDUSTRY_OLIVE, INDUSTRY_SAWMILL, INDUSTRY_SCULPTURE, INDUSTRY_WINERY,

    CULTURE_PODIUM, CULTURE_COLLEGE, CULTURE_THEATER, CULTURE_SCHOOLTHEATER

}
